package com.dat3m.dartagnan.verification.solving;

public enum QueueType{
    RELATIONS_SHUFFLE, RELATIONS_SORT, SINGLE_LITERAL, EMPTY, MUTUALLY_EXCLUSIVE_SORT, MUTUALLY_EXCLUSIVE_SHUFFLE, EVENTS, MUTUALLY_EXCLUSIVE_EVENTS;
}
