package com.dat3m.dartagnan.verification.solving;

public enum QueueType{
    RELATIONS_SHUFFLE, RELATION_DEFAULT, RELATIONS_SORT, SINGLE_LITERAL, EMPTY, MUTUALLY_EXCLUSIVE_SORT, MUTUALLY_EXCLUSIVE_SHUFFLE, EVENTS, EVENTS_SHUFFLE, MUTUALLY_EXCLUSIVE_EVENTS, OLD_RELATION, OLD_EVENTS;
}

